name: CreativeNbtControl
main: net.craftersland.creativeNBT.CC
version: 1.16
author: CraftersLand
website: www.craftersland.net
load: STARTUP
description: Control over creative NBT data copy function.
api-version: 1.13
commands:
    cnc:
        description: The main command.
permissions:
    CNC.admin:
        description: Admin commands access
        default: op
    CNC.bypass:
        description: Unlock access to creative NBT copy feature.
        default: op
    CNC.bypass.enchants:
        description: Unlock access to copy enchants.
        default: op
    CNC.bypass.itemframes:
        description: Unlock access to interact with itemframe in Creative Mode.
        default: op
    CNC.bypass.armorstands:
        description: Unlock access to interact with armorstand in Creative Mode.
        default: op
